version: '3.8'

services:
  genocide-service:
    build: ./first-service
    container_name: first-service
    networks:
      - services-network 
    depends_on:
      - localhost
    ports:
      - "8080:8080"

  # soa-service:
  #   build: ./second-service
  #   container_name: second-service
  #   networks:
  #     - services-network
  #   # depends_on:
  #   #   - main-db
  #   ports:
  #     - "9090:9090"

  localhost:
    image: postgres
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "54323:54323"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=soa

networks:
  services-network:
    driver: bridge